version: '3.8'

services:
  postgres:
    image: postgres:17-bookworm
    container_name: nelon_shift_db
    restart: always
    environment:
      POSTGRES_DB: nelon_shift
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nelon_net

volumes:
  postgres_data:

networks:
  nelon_net:
